---

- name: neovim setup
  package:
    name: neovim
    state: present
  become: true

- name: plug setup
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ default_user.home}}/.config/nvim/autoload/plug.vim"
