---
# tasks file for account

- name: "setup {{ default_user.username }}"
  user:
    name: "{{ default_user.username }}"
    shell: "{{ default_user.shell }}"
    append: true
    groups: "{{ default_user.groups }}"
    home: "{{ default_user.home }}"

- name: configure git
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: "{{ item.scope }}"
  loop: "{{ git_configs }}"
