- hosts: all
  roles:
    - role: ../roles/account
    - role: ../roles/dotfiles
    - role: ../roles/neovim
    - role: ../roles/packages
    - role: ../roles/gh
    - role: ../roles/docker
    - role: ../roles/oh-my-bash
- hosts: kaffi
  roles:
    - role: ../roles/minikube
